---
title: "Your Project Title"
author: "Group members"
output: pdf_document
#output: html_document
fontsize: 10pt
geometry: margin=1in
---

```{r setup, include=FALSE}
#library(usethis)
library(ggmap)
library(rgdal)
library(here)
library(proj4)
library(magrittr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(magick)
library(png)
library(ggimage)
library(mapdeck)
library(osmdata)
library(maps)
#library(sf)
library(grid)
library(gridBase)

#Parking_Citations <- readRDS(file = "/Users/mattbarclay/Desktop/Junior/Spring/STAT 405/Parking_Citations_Cleaned.rds")
```

## cleaning data

```{r cleanup, eval=FALSE, include=FALSE, echo=FALSE}
#will not run with eval = FALSE
locs <- Parking_Citations%>%filter(!is.na(Latitude), !is.na(Fine.amount), Latitude > 99999)%>%select(Latitude, Longitude, Ticket.number)
coordinates(locs) <- ~ Latitude + Longitude
proj4string(locs) <- CRS("+init=esri:102645")
locs <- spTransform(locs, CRS("+init=epsg:4326"))%>%as.data.frame()%>%filter(Latitude < 0)%>%select(real_lng = Latitude, real_lat = Longitude, Ticket.number = Ticket.number)
df <- Parking_Citations%>%filter(!is.na(Latitude), !is.na(Fine.amount), Latitude > 99999)%>%
  left_join(locs)
#saveRDS(df, file = "Parking_Citations_Cleaned.rds")
```

```{r eval = FALSE, include=FALSE, echo=FALSE}

## Creates locations and a heatmap of data on the map of LA
locs <- Parking_Citations %>%
  filter(!is.na(Latitude), Latitude > 99999) %>%
  select(Latitude, Longitude)
coordinates(locs) <- ~ Latitude + Longitude
proj4string(locs) <- CRS("+init=esri:102645")
locs <- spTransform(locs,CRS("+init=epsg:4326")) %>%
  as.data.frame()
locs2 <- locs[seq(4000000:4100000),]
```

```{r, echo=FALSE}
map <- get_map(getbb("Los Angeles"), zoom = 10, map_type = "roadmap")
ggmap(map) +
  stat_density2d(data = Parking_Citations_Cleaned[4000000:5000000,], aes(x = real_lng, y = real_lat, fill = ..level.., alpha = ..level..), geom = "polygon", size = 0.01, bins = 16) +
  scale_fill_gradient(low = "red", high = "yellow") +
  scale_alpha(range = c(0, 1), guide = FALSE)
```

```{r, echo=FALSE}
#Average fine amount by car Color
Parking_Citations[1:1000, 1:22] %>% 
  filter(!is.na(Fine.amount), !is.na(Color)) %>%
  group_by(Color) %>%
  summarise(avg = mean(Fine.amount), count = n()) %>%
  subset(Color == "RD" | Color == "GY" | Color =="WH" | Color == "BL" | Color == "BK" | Color == "BN") %>% 
  transmute(Color = Color, avg = avg) %>%
  ggplot() + aes(x = Color, y = avg, fill = Color) + geom_histogram(stat = "identity") +
  labs(title = "Average fine amount by car color", x = "Car Color", y = "Average Fine Amount ($)") +
  theme(axis.text.x.bottom = element_text(hjust = 1, angle = 45, size = 8),
        legend.position = "none") +
  scale_x_discrete(labels = c("Black", "Blue", "Brown", "Gray", "Red", "White")) +
  scale_fill_manual(values = c("Black", "Blue", "Saddle Brown", "Gray", "Red", "White"))
```

```{r holidays, echo=FALSE}
holidays <- c("12/25/2014", "12/25/2015", "12/25/2016", "12/25/2017", "12/25/2018", "12/25/2019", 
              "12/31/2014", "12/31/2015", "12/31/2016", "12/31/2017", "12/31/2018", "12/31/2019", 
              "11/27/2014", "11/26/2015", "11/24/2016", "11/23/2017", "11/22/2018", "11/28/2019",
              "10/31/2014", "10/31/2015", "10/31/2016", "10/31/2017", "10/31/2018", "10/31/2019",
              "06/04/2014", "06/04/2015", "06/04/2016", "06/04/2017", "06/04/2018", "06/04/2019",
              "02/14/2014", "02/14/2015", "02/14/2016", "02/14/2017", "02/14/2018", "02/14/2019",
              "03/17/2014", "03/17/2015", "03/17/2016", "03/17/2017", "03/17/2018", "03/17/2019",
              "02/02/2014", "02/01/2015", "02/07/2016", "02/05/2017", "02/04/2018", "02/03/2019")
holiday_names <- data.frame(date= c("02/14", "03/17", "06/04", "10/31", "11/22", "11/23", "11/24", "11/26","11/27", "11/28", "12/25", "12/31", "02/02", "02/01", "02/07", "02/05", "02/04", "02/03"), 
                            name = c("Valentine's", "St. Patricks", "July 4th", "Halloween", rep("Thanksgiving", 6), "Christmas", "New Years", rep("Super Bowl Sunday", 6)))

h_parking <- Parking_Citations%>%filter(Issue.Date %in% holidays)%>%
              mutate(date = format(as.Date(Issue.Date, format = "%m/%d/%Y"), format="%m/%d"))%>%
              left_join(holiday_names, by = 'date')


h_parking <- h_parking%>%group_by(name)%>%summarise(mean = mean(Fine.amount), sum_prop = sum(Fine.amount)/1965659, count = n()) 

grid.newpage()
vp <- viewport(height = 4, width = 10, default.units = "cm")
pushViewport(vp)
grid.circle(x = rep(seq(1, 9, length.out = 4), 2), y = c(rep(0.5, 4), rep(3.5, 4)), r = h_parking$sum_prop, default.units = "cm", vp = vp)
grid.text(h_parking$name, x = rep(seq(1, 9, length.out = 4), 2), y = c(rep(0, 4), rep(4, 4)), default.units = "cm", vp = vp, gp = gpar(cex = 0.5))

```

```{r}
## creates sql weather comparison graph
library(RSQLite)
dcon <- dbConnect(SQLite(), dbname = "C:/Users/Galle/Desktop/RProjects/STAT 405/STAT 405 Data/data.sqlite")
dbListTables(dcon)

mydf <- dbSendQuery(conn = dcon, "
SELECT *
FROM LA_Weather;
") %>%
  dbFetch(-1) %>%
  filter(PRCP >= .5)
dbDisconnect(dcon)

test <- Parking_Citations_Cleaned %>%
  filter(as.Date(Parking_Citations_Cleaned$Issue.Date, format = "%m/%d/%Y")
         %in%
          as.Date(mydf$DATE))

map <- get_map(getbb("Los Angeles"), zoom = 10, map_type = "roadmap")
ggmap(map) +
  stat_density2d(data = test, aes(x = real_lng, y = real_lat, fill = ..level.., alpha = ..level..), geom = "polygon", size = 0.01, bins = 16) +
  scale_fill_gradient(low = "red", high = "yellow") +
  scale_alpha(range = c(0, 1), guide = FALSE)

```


